server:
  port: 8080

logging:
  level:
    learning: trace
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ALON_FANFAN
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    connectionProperties:
      druid:
      stat:
      mergeSql: true

  freemarker:
    #关闭缓存
    cache: false
    request-context-attribute: request
    #模板加载的位置
    template-loader-path: classpath:/templates
    #前缀
    suffix: .htm
    #后缀
    prefix: /htm/


mybatis:
  #实体类所做包
  type-aliases-package: com.fanfan.alon.models
  #mapper.xml所在位置
  mapper-locations: classpath:/mappers/*.xml
