server:
  port: 9000

logging:
  level:
    learning: trace
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ALON_FANFAN?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    connectionProperties:
      druid:
      stat:
      mergeSql: true

  freemarker:
    #关闭缓存
    cache: false
    request-context-attribute: request
    #模板加载的位置
    template-loader-path: classpath:/templates/
    enabled:  true
    charset:  UTF-8
    #后缀名
    suffix: .html
    #
    prefix:


mybatis:
  #实体类所做包
  type-aliases-package: com.fanfan.alon.models
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名规范
  #mapper.xml所在位置prefix
  mapper-locations: classpath:/mappers/*.xml
